### ISSUE TITLE
Content Install fails [You do not have sufficient permissions to access this page]

### ISSUE THREAD

**Issue by NazarkinRoman** [ThemeFuse/Unyson-Backup-Extension#13]
Hi.

After installing & activating my theme and unyson plugin I have **Content install** item under **Tools** menu. Once process is finished(no messages is being displayed, I saw new files in uploads directory and new items in database) but I cannot access **any** page in dashboard. 
WordPress says: _You do not have sufficient permissions to access this page._

What I did wrong and how I can fix this behavior(to my users are not faced same bug)?
Thanks.

**Comment by NazarkinRoman** [comment]
Investigated that importer renamed some fields in `wp_usermeta` table and somewhere else. So, right field name is `wp_capabilities`, after import it was converted to `wp_pref_pref_pref_capabilities`(`_pref` is my table prefix, but here it repeated three times). So, WP are not use these fields properly.

And take a look [here](http://stackoverflow.com/a/13815934/1349677), may be there is need to perform these queries right after demo content imported into the tables?

**Comment by valeriuzdrobau** [comment]
Hello, starting with version [1.0.6](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.6) I made [some changes](https://github.com/ThemeFuse/Unyson-Backup-Extension/commit/d08e4f3ecb81d4db805e52bb65e9438fcda3ab5d) to keep`usermeta` table because it keeps data about users.
  To not met after import this message: **_You do not have sufficient permissions to access this page**_, please perform the following steps:
1. Make sure that you use 1.0.6 or newer version of backup extension;
2. If the demo content was created using an older version than [1.0.6](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.6), then you must enter in `{theme_root} /auto-install/database.txt` file, and at the end of this file, you need to find code that respond for importing `usermeta` table, you need to remove him;
   If you have already imported content and do not have access to the dashboard because encounter the message: _You do not have sufficient permissions to access this page_, you need to import your own `usermeta`. On every import demo content, `backup` extension creates a reserve copy of files and database. These copies are saved in the folder `wp-content/uploads/backup/` with a name like this: `backup-2015_07_10-20_01_55-6fbf93d48835.zip`. In this archive, you will find in root folder the `database.txt` file (that file contain your database after import process), and near the end you will find the code that needs to import to get `usermeta` table with data for your WordPress instance. After this import, you should have access to your dashboard.

@NazarkinRoman I understand that at you exists some problems with imported prefix, but still follow the steps above and let me know about the results.

**Comment by NazarkinRoman** [comment]
@valeriuzdrobau I have updated backup extension to the `1.0.6` version(latest), recreated auto-install archive and imported demo data on the new site and.. get the same error. Column `meta_key` in `wp_postmeta` table is being updated with three-times repeated prefix and `wp_options` table updated with two-times repeated prefix. 

PHPMyAdmin screenshot - http://s1.micp.ru/adfqz.png

**Comment by valeriuzdrobau** [comment]
ok, which is the prefix for your tables? I want to reproduce this problem on local.

**Comment by NazarkinRoman** [comment]
@valeriuzdrobau on development installation table prefix is default - `wp_` and on production - `wp_acrc_`.

**Comment by NazarkinRoman** [comment]
Thanks for a instant fix! Awesome!

But one more question: I need to update extension on both installations or on development only?

**Comment by valeriuzdrobau** [comment]
only on production.

**Comment by NazarkinRoman** [comment]
Ok, when this changes will go to release, so my end users can download a fixed version to their own  sites via built-in extension update mechanism?

**Comment by valeriuzdrobau** [comment]
Yes, the changes are reflected in  [1.0.7 version](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.7).
