### ISSUE TITLE
Issues with the content install

### ISSUE THREAD

**Issue by cristeacosmin** [ThemeFuse/Unyson-Backup-Extension#21]
The demo content installs using the URLS from the development environment, do I need to run a query to change these myself or am I missing something?

If so, can I hook in the "saving" process and change the URLS at that particular time ? So I don't have to create a button or a notification of some sort.

Thanks for your help.

**Comment by ghost** [comment]
Hello,

Currently we are working on Backup v2, it should be finished in 2 weeks and it should fix all issues related to backup and demo content.

Regarding this issue I can't answer because I am not familiar with how current Backup v2 internals work.

I can only recommend to update manually all urls in database (using some sort of script or a soft that does such things).

**Comment by cristeacosmin** [comment]
Hello,

Thanks for getting back so quickly!

Will wait for the new version :)
